language: node_js
node_js:
  - 10
  - 8

cache:
  directories:
    - node_modules/

install:
  - yarn

script:
  - yarn test
  - yarn run build

# Uncomment these lines if you want to enable code coverage
# after_script:
#   - cat coverage/lcov.info | coveralls